<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.Postgresql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModularVerticalSlice.Application\ModularVerticalSlice.Application.csproj" />
    <ProjectReference Include="..\ModularVerticalSlice.Persistence\ModularVerticalSlice.Persistence.csproj" />
    <ProjectReference Include="..\ModularVerticalSlice.SharedKernel\ModularVerticalSlice.SharedKernel.csproj" />
  </ItemGroup>

</Project>
