<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModularVerticalSlice.Application\ModularVerticalSlice.Application.csproj" />
    <ProjectReference Include="..\ModularVerticalSlice.Persistence\ModularVerticalSlice.Persistence.csproj" />
    <ProjectReference Include="..\ModularVerticalSlice.SharedKernel\ModularVerticalSlice.SharedKernel.csproj" />
  </ItemGroup>

</Project>
