<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ModularVerticalSlice.Application\ModularVerticalSlice.Application.csproj" />
    <ProjectReference Include="..\..\src\ModularVerticalSlice.Persistence\ModularVerticalSlice.Persistence.csproj" />
    <ProjectReference Include="..\..\src\ModularVerticalSlice.SharedKernel\ModularVerticalSlice.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\ModularVerticalSlice.WebApi\ModularVerticalSlice.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\src\ModularVerticalSlice.WebApi\appsettings.Development.json"
             Link="appsettings.Development.json"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
